controller_manager:
  ros__parameters:
    update_rate: 50

    skid_steer:
      type: diff_drive_controller/DiffDriveController

    broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

skid_steer:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'back_right_wheel_joint']
    wheel_separation: 0.212
    wheel_radius: 0.06

    use_stamped_vel: false

    wheels_per_side: 2
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    
    enable_odom_tf: false
