tracker:
  ros__parameters:
    x: 0
    y: 30
    width: 100
    height: 100
    min_size: 3
    max_size: 100
    min_hue: 54
    max_hue: 87
    min_sat: 66
    max_sat: 255
    min_val: 0
    max_val: 255

    calibration_mode: false
    experiment_mode: true

    obj_timeout: 1.0
    obj_max_size: 0.05

    linear_speed: 0.1
    angular_speed: 0.7
    
    search_speed: 0.3
    
