tracker:
  ros__parameters:
    # tuning_mode: false # Could set this here but leave it off so it can be easily set by the launch script
    x_min: 0
    x_max: 100
    y_min: 30
    y_max: 100
    h_min: 54
    h_max: 87
    s_min: 66
    s_max: 255
    v_min: 0
    v_max: 255
    sz_min: 3
    sz_max: 100

    rcv_timeout_secs: 1.0
    angular_chase_multiplier: 0.7
    forward_chase_speed: 0.1
    search_angular_speed: 0.3
    max_size_thresh: 0.05
    filter_value: 0.9
    
